INITIAL_CASH=100000

DATA_PATH='data/'
DATA_STOCKS_PATH='data/stocks/'
OUTPUT_REPORTS_PATH='outputs/reports/'
OUTPUT_ANALYSIS_FIGURES_PATH='outputs/analysis/figures/'
OUTPUT_ANALYSIS_PATH='outputs/analysis/'


STRATEGY_TICKERS = ['AAPL', 'MSFT', 'GOOGL', 'TSLA']
INIT_DATE='2021-01-01'
END_DATE='2022-01-01'